name: Pull-request Helper

on:
  issue_comment:
    types: [created, edited]

jobs:
  merge:
    if: ${{ (github.event.issue.pull_request) && (github.event.comment.body == '/merge') }}
    runs-on: ubuntu-22.04
    permissions: {}
    timeout-minutes: 3
    steps:
      - uses: abema/github-actions-merger@deps-change-distroless-base-to-static
        with:
          github_token: ${{ secrets.GH_PAT }}
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.issue.number }}
          comment: ${{ github.event.comment.body }}
